name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME_DJ }}
        run: sudo docker pull $DOCKER_USER/bike_rental_prediction:latest

      - name: Delete Old Docker Container
        run: sudo docker rm -f bike_rental_container || true

      - name: Run Docker Container
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME_DJ }}
        run: sudo docker run -d -p 8000:8000 --name bike_rental_container $DOCKER_USER/bike_rental_prediction:latest
